Pig Stack Trace
---------------
ERROR 6000: 
<file exp3.pig, line 6, column 0> Output Location Validation Failed for: '/users/curtisu/Lab5/exp3/firewall4 More info to follow:
Output directory /users/curtisu/Lab5/exp3/firewall4 already exists

org.apache.pig.impl.plan.VisitorException: ERROR 6000: 
<file exp3.pig, line 6, column 0> Output Location Validation Failed for: '/users/curtisu/Lab5/exp3/firewall4 More info to follow:
Output directory /users/curtisu/Lab5/exp3/firewall4 already exists
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:95)
	at org.apache.pig.newplan.logical.relational.LOStore.accept(LOStore.java:77)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:64)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.walk(DepthFirstWalker.java:53)
	at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:50)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator.validate(InputOutputFileValidator.java:45)
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.compile(HExecutionEngine.java:292)
	at org.apache.pig.PigServer.compilePp(PigServer.java:1360)
	at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1297)
	at org.apache.pig.PigServer.execute(PigServer.java:1286)
	at org.apache.pig.PigServer.executeBatch(PigServer.java:360)
	at org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:131)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:192)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:164)
	at org.apache.pig.tools.grunt.Grunt.exec(Grunt.java:81)
	at org.apache.pig.Main.run(Main.java:553)
	at org.apache.pig.Main.main(Main.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:156)
Caused by: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory /users/curtisu/Lab5/exp3/firewall4 already exists
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:134)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:80)
	... 25 more
================================================================================
